name: Writing Own Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - id: build
        name: Build
        run: dotnet build --no-restore

      - id: test
        if: steps.build.outcome == 'success'
        name: Test
        run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura --no-build --verbosity normal

      - id: coverage
        name: Code Coverage Report
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Cobertura report (with packages)
        run: |
          set -e
          REPORTS=$(find . -type f -name 'coverage.cobertura.xml' -path "./**/TestResults/*/coverage.cobertura.xml" -print | tr '\n' ',')
          if [ -z "$REPORTS" ]; then
            echo "No coverage files found"
            exit 0
          fi
          reportgenerator -reports:"$REPORTS" -targetdir:coverage-report -reporttypes:Cobertura

      - id: coverage
        name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coverage-report/Cobertura.xml"
          badge: false
          fail_below_min: false
          hide_branch_rate: false
          hide_complexity: true
          output: console
